#!/bin/bash

echo -e "\033[1;31mATENCION!!\033[0m"
echo " "
echo -e "\033[1;33mEsa contraseña sera usada para entrar en su servidor
\033[0m"
echo -e "\033[1;32mDIGITE LA NUEVA CONTRASEÑA \033[1;32m
para continuar...\033[1;31m\033[0m"
read  -p : pass
(echo $pass; echo $pass)|passwd 2>/dev/null
sleep 1s
echo -e "\033[1;31mCONTRASEÑA ALTERADA CON EXITO!\033[0m"
sleep 5s
cd
clear

